### ISSUE TITLE
Compile environment problem

### ISSUE THREAD

**Issue by dataalliance** [SamsungARTIK/u-boot-artik#1]
This project have a problem

env : ARTIK053S

**make CROSS_COMPILE=arm-none-eabi-**

will cause error

**/bin/sh: 1: dtc: not found
scripts/Makefile.lib:322: 'arch/arm/dts/exynos0200-artik051.dtb' 타겟에 대한 명령이 실패했습니다
make[2]: *** [arch/arm/dts/exynos0200-artik051.dtb] 오류 127
dts/Makefile:36: 'arch-dtbs' 타겟에 대한 명령이 실패했습니다
make[1]: *** [arch-dtbs] 오류 2
Makefile:1217: 'dts' 타겟에 대한 명령이 실패했습니다
make: *** [dts] 오류 2**

**Comment by JunhwanPark** [comment]
Hi @dataalliance ,

U-boot has a module that uses the `device tree compiler (DTC)`, so you need to install it to build the module.
```tash
$ sudo apt-get install device-tree-compiler
```
In the next update I will write the above in the README.
Thanks,
