### ISSUE TITLE
fastboot could not find device

### ISSUE THREAD

**Issue by csj0202** [SamsungARTIK/u-boot-artik#2]
I follow the README.md to change new u-boot into Artik533s but there are some problems.
At README-3.1 install fast boot sequence, wget command make 404 error
s@cs533s/build-artik$ wget -S -O - http://source.android.com/source/51-android.rules | sed "s/<username>/$USER/" | sudo tee >/dev/null /etc/udev/rules.d/51-android.rules; sudo udevadm control --reload-rules
URL transformed to HTTPS due to an HSTS policy
--2018-03-05 16:04:36--  https://source.android.com/source/51-android.rules
Connecting to 10.112.1.184:8080... connected.
Proxy request sent, awaiting response... 
  HTTP/1.1 301 Moved Permanently
  X-XSS-Protection: 1; mode=block
  Content-Language: en
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000; includeSubdomains
  Vary: Accept-Language
  Location: https://source.android.com/setup/51-android.rules
  X-Frame-Options: SAMEORIGIN
  Content-Type: text/html; charset=utf-8
  X-Cloud-Trace-Context: 9d881959cec99493f7a5268830fe4b3b
  Date: Mon, 05 Mar 2018 07:04:37 GMT
  Server: Google Frontend
  Content-Length: 0
  Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
  Connection: close
Location: https://source.android.com/setup/51-android.rules [following]
--2018-03-05 16:04:37--  https://source.android.com/setup/51-android.rules
Connecting to 10.112.1.184:8080... connected.
Proxy request sent, awaiting response... 
  HTTP/1.1 404 Not Found
  Strict-Transport-Security: max-age=31536000; includeSubdomains
  Content-Language: en
  X-Content-Type-Options: nosniff
  Expires: Mon, 05 Mar 2018 08:04:38 GMT
  Vary: Accept-Language
  Last-Modified: Mon, 05 Mar 2018 07:04:38 GMT
  X-XSS-Protection: 1; mode=block
  Cache-Control: max_age=3600, public, must-revalidate
  X-Frame-Options: SAMEORIGIN
  Content-Type: text/html; charset=utf-8
  X-Cloud-Trace-Context: 2a483345738e87d4acdae4747cb3a56d
  Date: Mon, 05 Mar 2018 07:04:38 GMT
  Server: Google Frontend
  Content-Length: 22339
  Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
  Connection: close
2018-03-05 16:04:39 ERROR 404: Not Found.

can you give me correct URL?

**Comment by cometzero** [comment]
Hi,

The source url has been removed and I can't find proper url to download it.
Could you run below script instead of the original one?

sudo curl --create-dirs -L -o /etc/udev/rules.d/51-android.rules -O -L https://raw.githubusercontent.com/snowdream/51-android/master/51-android.rules
sudo udevadm control --reload-rules

**Comment by csj0202** [comment]
thanks. but I already found the rule file at here
https://github.com/M0Rf30/android-udev-rules
